function Hd = getFilter
%GETFILTER Returns a discrete-time filter System object.

% MATLAB Code
% Generated by MATLAB(R) 23.2 and DSP System Toolbox 23.2.
% Generated on: 14-Jan-2025 12:59:05

Fstop1 = 1;    % First Stopband Frequency
Fpass1 = 2;    % First Passband Frequency
Fpass2 = 48;   % Second Passband Frequency
Fstop2 = 92;   % Second Stopband Frequency
Astop1 = 40;   % First Stopband Attenuation (dB)
Apass  = 1;    % Passband Ripple (dB)
Astop2 = 40;   % Second Stopband Attenuation (dB)
Fs     = 500;  % Sampling Frequency

h = fdesign.bandpass('fst1,fp1,fp2,fst2,ast1,ap,ast2', Fstop1, Fpass1, ...
    Fpass2, Fstop2, Astop1, Apass, Astop2, Fs);

Hd = design(h, 'butter', ...
    'FilterStructure', 'df1sos', ...
    'MatchExactly', 'stopband', ...
    'SystemObject', true,...
    UseLegacyBiquadFilter=true);


